# Generated by Django 2.0 on 2019-04-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time']},
        ),
        migrations.RenameField(
            model_name='blogtype',
            old_name='Type_name',
            new_name='type_name',
        ),
    ]
