# Generated by Django 2.0 on 2019-04-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190410_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views_num',
            field=models.IntegerField(default=0),
        ),
    ]
